# Generated by Django 4.1.7 on 2023-02-22 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PositionMark',
            new_name='PositionDuty',
        ),
        migrations.AlterField(
            model_name='position',
            name='employee',
            field=models.ManyToManyField(related_name='positions', to=settings.AUTH_USER_MODEL, verbose_name='сотрудники'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.DeleteModel(
            name='PositionAdditionalMark',
        ),
    ]
