# Generated by Django 4.1.7 on 2023-02-26 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_positionmark_positionduty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionduty',
            options={'verbose_name': 'смена', 'verbose_name_plural': 'смены'},
        ),
        migrations.AddField(
            model_name='positionduty',
            name='days',
            field=models.IntegerField(default=0, verbose_name='кол-во суток в смене'),
        ),
        migrations.AddField(
            model_name='positionduty',
            name='end',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='конец смены'),
        ),
        migrations.AddField(
            model_name='positionduty',
            name='price',
            field=models.IntegerField(default=500, verbose_name='цена смены'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionduty',
            name='price_add',
            field=models.IntegerField(default=500, verbose_name='цена часа переработки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionduty',
            name='price_km',
            field=models.IntegerField(default=500, verbose_name='цена км за МКАД'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionduty',
            name='start',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='начало смены'),
        ),
        migrations.AlterField(
            model_name='positionduty',
            name='date',
            field=models.DateField(verbose_name='дата смены'),
        ),
        migrations.AlterField(
            model_name='positionduty',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.position', verbose_name='должность'),
        ),
    ]
