# Generated by Django 4.1.7 on 2023-02-26 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_positionduty_options_positionduty_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionduty',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата смены'),
        ),
    ]
