# Generated by Django 4.1.7 on 2023-02-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_positionduty_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionduty',
            name='km',
            field=models.IntegerField(default=0, verbose_name='км за МКАД'),
        ),
    ]
