# Generated by Django 4.1.7 on 2023-02-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_positionduty_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.AlterField(
            model_name='positionduty',
            name='position',
            field=models.CharField(max_length=255, verbose_name='должность'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
