# Generated by Django 4.1.7 on 2023-02-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_project_owner_alter_positionduty_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionduty',
            name='dinner',
            field=models.BooleanField(default=False, verbose_name='Текущий обед'),
        ),
    ]
