# Generated by Django 4.1.7 on 2023-02-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_positionduty_dinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionduty',
            name='hours',
            field=models.IntegerField(default=12, verbose_name='кол-во часов смены'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionduty',
            name='hours_add',
            field=models.IntegerField(default=12, verbose_name='кол-во часов переработки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='positionduty',
            name='price',
            field=models.IntegerField(verbose_name='цена часа смены'),
        ),
    ]
