# Generated by Django 4.1.7 on 2023-02-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_positionduty_hours_positionduty_hours_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionduty',
            name='hours',
        ),
    ]
