# Generated by Django 4.1.7 on 2023-02-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_remove_positionduty_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionduty',
            name='hours_duty',
            field=models.IntegerField(default=9, verbose_name='длительность смены (ч)'),
        ),
    ]
