# Generated by Django 4.1.7 on 2023-03-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_positionduty_hours_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionduty',
            name='hours_since_last',
            field=models.IntegerField(default=12, verbose_name='разрыв между сменами'),
        ),
    ]
