# Generated by Django 4.1.7 on 2023-03-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_positionduty_hours_since_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionduty',
            name='hours_since_last',
            field=models.FloatField(default=12, verbose_name='разрыв между сменами'),
        ),
    ]
