# Generated by Django 4.1.7 on 2023-03-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_positionduty_hours_since_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionduty',
            name='dinner',
        ),
        migrations.AddField(
            model_name='positionduty',
            name='dinner_fluent',
            field=models.IntegerField(default=2, verbose_name='Текущий обед (ч)'),
        ),
        migrations.AddField(
            model_name='positionduty',
            name='dinner_late',
            field=models.IntegerField(default=0, verbose_name='Поздний обед (ч)'),
        ),
    ]
