# Generated by Django 4.1.7 on 2023-03-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_remove_positionduty_dinner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positionduty',
            old_name='dinner_fluent',
            new_name='hours_dinner_fluent',
        ),
        migrations.RenameField(
            model_name='positionduty',
            old_name='dinner_late',
            new_name='hours_dinner_late',
        ),
    ]
