# Generated by Django 4.1.7 on 2023-03-08 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0017_rename_dinner_fluent_positionduty_hours_dinner_fluent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('employees', models.ManyToManyField(related_name='projects_employee', to=settings.AUTH_USER_MODEL, verbose_name='сотрудники')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_owner', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
        ),
        migrations.AddField(
            model_name='positionduty',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.project', verbose_name='Проект'),
        ),
    ]
